export const FETCH_EPISODE_REQUEST = 'FETCH_EPISODE_REQUEST';
export const FETCH_EPISODE_SUCCESS = 'FETCH_EPISODE_SUCCESS';
export const FETCH_EPISODE_FAILED = 'FETCH_EPISODE_FAILED';

//episode details actions
export const FETCH_EPISODE_DETAILS_REQUEST = 'FETCH_EPISODE_DETAILS_REQUEST';
export const FETCH_EPISODE_DETAILS_SUCCESS = 'FETCH_EPISODE_DETAILS_SUCCESS';
export const FETCH_EPISODE_DETAILS_FAILED = 'FETCH_EPISODE_DETAILS_FAILED';
